name:    rmeoc-oauth2-client
version: "0.0.0"

dependencies:
- aeson
- aeson-casing
- base
- binary
- bytestring
- either
- hoauth2
- http-client
- http-types
- lens
- mtl
- newtype
- nonce
- semigroupoids
- text
- time
- unliftio
- uri-bytestring
- yesod-core

library:
  source-dirs: src
  exposed-modules:
    - OAuth2Client
  ghc-options:
    - -Wall
